services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?schema=public
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ADMIN_ROOT_EMAIL: ${ADMIN_ROOT_EMAIL}
      ADMIN_ROOT_PASSWORD: ${ADMIN_ROOT_PASSWORD}
    ports:
      - 3333:3333
    networks:
      - papelito
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    user: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
    restart: unless-stopped
    networks:
      - papelito
    healthcheck:
      test: [ "CMD", "pg_isready", "-U ${DATABASE_USERNAME}", "-d ${DATABASE_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:

networks:
  papelito:
    driver: bridge
